# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='political_orientation',
            field=models.CharField(default='Democrat', max_length=255, verbose_name='Political Orientation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='race',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('native_american', 'American Indian/Alaska Native'), ('asian', 'Asian'), ('pacific_island', 'Native Hawaiian/Other Pacific Islander')], default='white', max_length=50, verbose_name='Race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(default='none', max_length=255, verbose_name='Religion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1, verbose_name='Sex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_education_completed',
            field=models.PositiveIntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.PositiveIntegerField(default=55555),
            preserve_default=False,
        ),
    ]
