# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0003_auto_20170611_1941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagepresentation',
            unique_together=set([('viewer', 'sequence_number')]),
        ),
    ]
